config/routes.rb
GeneradorOpengl::Application.routes.draw do
  get "archivos/index"
  get "archivos/new"
  get "archivos/:id" => 'archivos#show', as: 'archivo'
  post "archivos" => 'archivos#create'

  get "tarea2_v1" => 'archivos#tarea2_v1', as: 'tarea2'

  root 'archivos#new'

end

app/models/archivo.rb
class Archivo < ActiveRecord::Base
	validates_presence_of :nombre, :num_lados, :size_lados, message: "no puede estar vacio"

	validates :num_lados, :size_lados, numericality: { only_integer: true,  message: "no es un entero"}

	validates :tecla_tx, :tecla_ty, :tecla_tz, :tecla_sx,:tecla_sy,:tecla_sz,  :tecla_rx,:tecla_ry,:tecla_rz, length: { is: 1 }
	validates_presence_of :color_r, :color_g, :color_b, message: "Escoge un color"

	PI = 3.1416


	def include_glut
		'#include <gl/glut.h>'
	end
	def print_color
		"glColor3f(#{color_r.round(2)},#{color_g.round(2)},#{color_b.round(2)});"
	end


	def print_vectores
		@x = Array.new
		@y = Array.new
		radio = get_radio(size_lados, num_lados)
		genera_vectores(num_lados, radio)
		str = genera_texto_vectores(@x, @y, size_lados)
		str.split("\n")
	end

	private
	def genera_texto_vectores(vector_x, vector_y, size_lado)
		str = ""
		str += sprintf("%s","   //Cara frontal\n")
		(0...num_lados-1).each do |i|
			str += sprintf("\tglVertex3f(%5.2f, %5.2f,  #{size_lado/2.0});\n", vector_x[i], vector_y[i])
			str += sprintf("\tglVertex3f(%5.2f, %5.2f,  #{size_lado/2.0});\n", vector_x[i+1], vector_y[i+1])
		end
		str += sprintf("\tglVertex3f(%5.2f, %5.2f,  #{size_lado/2.0});\n", vector_x[num_lados-1], vector_y[num_lados-1])
		str += sprintf("\tglVertex3f(%5.2f, %5.2f,  #{size_lado/2.0});\n", vector_x[0], vector_y[0])

		str += sprintf("%s","   //Cara Posterior\n")
		(0...num_lados-1).each do |i|
			str += sprintf("\tglVertex3f(%5.2f, %5.2f, -#{size_lado/2.0});\n", vector_x[i], vector_y[i])
			str += sprintf("\tglVertex3f(%5.2f, %5.2f, -#{size_lado/2.0});\n", vector_x[i+1], vector_y[i+1])
		end
		str += sprintf("\tglVertex3f(%5.2f, %5.2f, -#{size_lado/2.0});\n", vector_x[num_lados-1], vector_y[num_lados-1])
		str += sprintf("\tglVertex3f(%5.2f, %5.2f, -#{size_lado/2.0});\n", vector_x[0], vector_y[0])

		str += sprintf("%s","   //Union de vertices entre las 2 caras\n")
		(0...num_lados).each do |i|
			str += sprintf("\tglVertex3f(%5.2f, %5.2f, -#{size_lado/2.0});\n", vector_x[i], vector_y[i])
			str += sprintf("\tglVertex3f(%5.2f, %5.2f,  #{size_lado/2.0});\n", vector_x[i], vector_y[i])
		end
		return str
	end


	def get_radio(size_lado, n_lados)
		# size_lado*Math.sin(2*PI/n_lados)
		size_lado/(2*Math.sin((2*PI)/(n_lados*2)))
	end

	def redondea(numero)
		numero.round(2)
	end

	def genera_vectores(n_lados, radio)
		ang_por_lado = (2*PI)/n_lados
	 	(0...n_lados).each do |i|
	 		@x << redondea((radio*Math.cos(i*( ang_por_lado ) - PI/4 )))
	 		@y << redondea((radio*Math.sin(i*( ang_por_lado ) - PI/4 )))
	 	end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/archivos_controller.rb
class ArchivosController < ApplicationController
  http_basic_authenticate_with name: "ronny", password: "seelmejor", except: [:show, :create, :new, :tarea2_v1]

  def index
  	@archivos = Archivo.all
  end

  def new
  	@archivo = Archivo.new
  end

  def create
  	@archivo = Archivo.new(archivo_params)
  	if @archivo.save
  		redirect_to @archivo
  	else
  		render "new"
  	end
  end

  def show
    @archivo =Archivo.find(params[:id])
    @archivo.visitas += 1
    @archivo.save
    unless @archivo.revisado
       @archivo.revisado = true
       @archivo.save
    else
       render "new"
    end
  end

  def tarea2_v1
  end

  private
  def archivo_params
     params.require(:archivo).permit(:nombre, :num_lados, :size_lados, :color_r, :color_g, :color_b, :tecla_tx, :tecla_ty, :tecla_tz, :tecla_sx,:tecla_sy,:tecla_sz,  :tecla_rx,:tecla_ry,:tecla_rz)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archivos_helper.rb
module ArchivosHelper
end

app/views/archivos/ejercicio2_v1.html.erb
<script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js"></script>

<script type="text/javascript">
$(document).ready(function(){

  $(document).ready(function() {
  	var clip = new ZeroClipboard($("#d_clip_button"))
  });

  $("#clear-test").on("click", function(){
    $("#fe_text").val("Copy me!");
    $("#testarea").val("");
  });
});

</script>
<div class="row">
  <div class="col-md-4">
	<p class="lead text-danger"><b>Ejercicio 2, primera versión:</b></p>
  </div>
  <div class="col-md-2 col-md-offset-4 text-right">
	  <button class='my_clip_button btn btn-success' data-clipboard-target='fe_text' data-clipboard-text='Default clipboard text from attribute' id='d_clip_button'>
	    Copia el código
	  </button>
  </div>
</div>
<pre class="prettyprint col-sm-10" id='fe_text'>
#include &#60;gl/glut.h&#62;

static float tz=0.0f;

static float cam=-15.0f;

void init(void);
void display(void);
void reshape(int, int);

void init(void){
	glClearColor(0.0,0.0,0.0,0.0);
	glShadeModel(GL_FLAT);
}

void dibujaFigura3D(){
   glutWireTeapot(5.0f);
}

void display(void){
	glClear(GL_COLOR_BUFFER_BIT);

		// Color
		glColor3f(0.38,0.73,1.0);
		dibujaFigura3D();

	glFlush();
}

void reshape(GLsizei w, GLsizei h){
	glViewport(0,0,w,h);
	glMatrixMode(GL_PROJECTION);
	glLoadIdentity();
	//glOrtho(-15,15,-15,15,-100,100);
    gluPerspective(60, 1, 0 , 100);
	gluLookAt(0,10,cam, 0,0,0, 0,1,0);
	glMatrixMode(GL_MODELVIEW);
}

void keyboard(unsigned char key, int x, int y){
     switch(key){
     	// controles para translacion
     	case 'e': tz += 0.3f;break;
     	case 'E': tz -= 0.3f;break;

     	case 'c': cam += 0.3f;break;
     	case 'C': cam -= 0.3f;break;
     }
     display();
     reshape(500,500);
}

int main(int argc, char** argv){
	glutInit(&argc, argv);
	glutInitDisplayMode(GLUT_SINGLE | GLUT_RGB);
	glutInitWindowSize(500,500);
	glutInitWindowPosition(100,100);
	glutCreateWindow("Ejercicio2");
	init();
	glutDisplayFunc(display);
	glutReshapeFunc(reshape);
	glutKeyboardFunc(keyboard);
	glutMainLoop();
	return 0;
}
</pre>
</div>

app/views/archivos/index.html.erb
<h1>Archivos Generados</h1>
<table>
	<thead>
		<th>
			<td>Nombre</td>
			<td></td>
		</th>
	</thead>
	<tbody>
	<% @archivos.each do |archivo| %>
		<tr>
			<td><%=link_to archivo.nombre, archivo %></td>
			<td></td>
		</tr>
	<% end %>
	</tbody>
</table>

<%= link_to 'Nuevo archivo', archivos_new_path %>

app/views/archivos/new.html.erb
<script type="text/javascript">
	function updateInfo(color) {
		document.getElementById('info-r').value = color.rgb[0];
		document.getElementById('info-g').value = color.rgb[1];
		document.getElementById('info-b').value = color.rgb[2];
	}
</script>

<h1 class="text-primary">Generador de archivos con OpenGL</h1>
<hr/>
<div class="row">
<div class="alert alert-info col-md-10">
<p>
	Escoge el nombre (lo que aparecerá en la barra de título), número de lados, la longitud de una arista, el color , y las teclas de control para cada transformación (rotación, escalado y traslación). Y tu poliedro estará listo.
</p>
<p>
	Todo es opcional menos el nombre y el color! Que lo disfruten.
</p>
</div>
</div>
<hr/>

<%= form_for :archivo, url: archivos_path,  html: {class: "form-horizontal", role: "form"} do |f| %>
<% if @archivo.errors.any? %>
<div class="row">
<div class="alert alert-danger col-md-10">
  <div id="error_explanation">
    <h2><%= pluralize(@archivo.errors.count, "error", "errores") %> hace que este formulario no se pueda enviar</h2>
    <ul>
    <% @archivo.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
</div>
</div>
<% end %>
<div class="form-group">
	<%= f.label :nombre, class: "col-sm-2 control-label" %>
	<div class="col-sm-8">
		<%= f.text_field  :nombre , class: "form-control"%>
	</div>
</div>

<div class="form-group">
	<%= f.label "Numero de lados", class: "col-sm-2 control-label" %>
	<div class="col-sm-8">
		<%= f.text_field  :num_lados , class: "form-control"%>
	</div>
</div>

<div class="form-group">
	<%= f.label "Longitud del lado", class: "col-sm-2 control-label" %>
	<div class="col-sm-8">
		<%= f.text_field  :size_lados , class: "form-control"%>
	</div>
</div>

<hr/>
	<div class="form-group">
		<label for="selector" class="col-sm-2 control-label">Color</label>
		<div class="col-sm-8">
			<input class="color {onImmediateChange:'updateInfo(this);'} form-control" value="66ff00"  class="form-control" id="selector">
		</div>
	</div>
<div class="form-inline" role="form">
	<div class="row">
		<div class="col-md-2 col-md-offset-2">
			<div class="form-group">
			<%= f.label "R", class: "col-xs-2" %></br>
			<%= f.text_field :color_r, id: "info-r", class: "form-control disabledInput" %>
			</div>
		</div>
		<div class="col-md-2 col-md-offset-1">
			<div class="form-group">
			<%= f.label "G", class: "col-xs-2" %></br>
			<%= f.text_field  :color_g, id: "info-g", class: "form-control" %>
			</div>
		</div>
		<div class="col-md-2 col-md-offset-1">
			<div class="form-group">
			<%= f.label "B", class: "col-xs-2" %></br>
			<%= f.text_field  :color_b, id: "info-b", class: "form-control" %>
			</div>
		</div>
	</div>
<hr/>

	<!-- Teclas de translacion -->
	<div class="row">
		<div class="col-md-offset-1">
			<h4>Teclas control de Traslación</h4>
		</div>
	</div>

	<div class="row">
		<div class="col-md-2 col-md-offset-2">
			<div class="form-group">
			<%= f.label "X", class: "col-xs-2" %>
			<%= f.text_field  :tecla_tx, id: "info-r", class: "form-control" %>
			</div>
		</div>
		<div class="col-md-2 col-md-offset-1">
			<div class="form-group">
			<%= f.label "Y", class: "col-xs-2" %></br>
			<%= f.text_field  :tecla_ty, id: "info-g", class: "form-control" %>
			</div>
		</div>
		<div class="col-md-2 col-md-offset-1">
			<div class="form-group">
			<%= f.label "Z", class: "col-xs-2" %></br>
			<%= f.text_field  :tecla_tz, id: "info-b", class: "form-control" %>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-offset-1">
			<h4>Teclas de control de Escalado</h4>
		</div>
	</div>

	<div class="row">
		<div class="col-md-2 col-md-offset-2">
			<div class="form-group">
			<%= f.label "X", class: "col-xs-2" %>
			<%= f.text_field  :tecla_sx, id: "info-r", class: "form-control" %>
			</div>
		</div>
		<div class="col-md-2 col-md-offset-1">
			<div class="form-group">
			<%= f.label "Y", class: "col-xs-2" %></br>
			<%= f.text_field  :tecla_sy, id: "info-g", class: "form-control" %>
			</div>
		</div>
		<div class="col-md-2 col-md-offset-1">
			<div class="form-group">
			<%= f.label "Z", class: "col-xs-2" %></br>
			<%= f.text_field  :tecla_sz, id: "info-b", class: "form-control" %>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-offset-1">
			<h4>Teclas de control de Rotación</h4>
		</div>
	</div>

	<div class="row">
		<div class="col-md-2 col-md-offset-2">
			<div class="form-group">
			<%= f.label "X", class: "col-xs-2" %>
			<%= f.text_field  :tecla_rx, id: "info-r", class: "form-control" %>
			</div>
		</div>
		<div class="col-md-2 col-md-offset-1">
			<div class="form-group">
			<%= f.label "Y", class: "col-xs-2" %></br>
			<%= f.text_field  :tecla_ry, id: "info-g", class: "form-control" %>
			</div>
		</div>
		<div class="col-md-2 col-md-offset-1">
			<div class="form-group">
			<%= f.label "Z", class: "col-xs-2" %></br>
			<%= f.text_field  :tecla_rz, id: "info-b", class: "form-control" %>
			</div>
		</div>
	</div>
</div>
<hr/>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      	<%= f.submit '>>> Quiero mi Archivo de OpenGL para el examen de CAD, ya! <<< XD', class: "btn btn-success btn-lg"%>
    </div>
</div>

<% end %>

<script type="text/javascript">
	function updateInfo(color) {
		document.getElementById('info-r').value = color.rgb[0];
		document.getElementById('info-g').value = color.rgb[1];
		document.getElementById('info-b').value = color.rgb[2];
	}
</script>

app/views/archivos/show.html.erb
<script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js"></script>

<script type="text/javascript">
$(document).ready(function(){

  $(document).ready(function() {
  	var clip = new ZeroClipboard($("#d_clip_button"))
  });

  $("#clear-test").on("click", function(){
    $("#fe_text").val("Copy me!");
    $("#testarea").val("");
  });
});

</script>
<div class="row">
  <div class="col-md-4">
	<p class="lead text-success">Feliz Navidad, aqui está Tu código:</p>
  </div>
  <div class="col-md-2 col-md-offset-4 text-right">
	  <button class='my_clip_button btn btn-primary' data-clipboard-target='fe_text' data-clipboard-text='Default clipboard text from attribute' id='d_clip_button'>
	    Copia el código
	  </button>
  </div>
</div>
<pre class="prettyprint col-sm-10" id='fe_text'>
<%= @archivo.include_glut %>

static float tx=0.0f, ty=0.0f, tz=0.0f;
static float sx=1.0f, sy=1.0f, sz=1.0f;
static float ax=0.0f, ay=0.0f, az=0.0f;

void init(void);
void display(void);
void reshape(int, int);

void init(void){
	glClearColor(0.0,0.0,0.0,0.0);
	glShadeModel(GL_FLAT);
}

void dibujaFigura3D(){
    glBegin(GL_LINES);
<% @archivo.print_vectores.each do |line| %>
<%= line%>
<% end %>
    glEnd();
}

void display(void){
	glClear(GL_COLOR_BUFFER_BIT);
	glPushMatrix();
		// traslacion
		glTranslatef(tx,ty,tz);
		// rotacion en cada eje
		glRotatef(ax,1, 0, 0);
		glRotatef(ay,0, 1, 0);
		glRotatef(az,0, 0, 1);
		// escalado
		glScalef(sx,sy,sz);
		// Color
		<%= @archivo.print_color %>
		dibujaFigura3D();
	glPopMatrix();
	glFlush();
}

void reshape(GLsizei w, GLsizei h){
	glViewport(0,0,w,h);
	glMatrixMode(GL_PROJECTION);
	glLoadIdentity();
	glOrtho(-15,15,-15,15,-100,100);
    //gluPerspective(60, 1, 0 , 10);
	gluLookAt(0,0,-7, 0,0,0, 0,1,0);
	glMatrixMode(GL_MODELVIEW);
}

void keyboard(unsigned char key, int x, int y){
     switch(key){
     	// controles para translacion
     	case '<%= @archivo.tecla_tx %>': tx += 0.3f;break;
     	case '<%= @archivo.tecla_tx.upcase %>': tx -= 0.3f;break;

     	case '<%= @archivo.tecla_ty %>': ty += 0.3f;break;
     	case '<%= @archivo.tecla_ty.upcase %>': ty -= 0.3f;break;

     	case '<%= @archivo.tecla_tz %>': tz += 0.3f;break;
     	case '<%= @archivo.tecla_tz.upcase %>': tz -= 0.3f;break;

     	// controles para escalado
     	case '<%= @archivo.tecla_sx %>': sx += 0.3f;break;
     	case '<%= @archivo.tecla_sx.upcase %>': sx -= 0.3f;break;

     	case '<%= @archivo.tecla_sy %>': sy += 0.3f;break;
     	case '<%= @archivo.tecla_sy.upcase %>': sy -= 0.3f;break;

     	case '<%= @archivo.tecla_sz %>': sz += 0.3f;break;
     	case '<%= @archivo.tecla_sz.upcase %>': sz -= 0.3f;break;

     	// controles para rotacion
     	case '<%= @archivo.tecla_rx %>': ax += 2.0f;break;
     	case '<%= @archivo.tecla_rx.upcase %>': ax -= 2.0f;break;

     	case '<%= @archivo.tecla_ry %>': ay += 2.0f;break;
     	case '<%= @archivo.tecla_ry.upcase %>': ay -= 2.0f;break;

     	case '<%= @archivo.tecla_rz %>': az += 2.0f;break;
     	case '<%= @archivo.tecla_rz.upcase %>': az -= 2.0f;break;
     }
     display();
}

int main(int argc, char** argv){
	glutInit(&argc, argv);
	glutInitDisplayMode(GLUT_SINGLE | GLUT_RGB);
	glutInitWindowSize(500,500);
	glutInitWindowPosition(100,100);
	glutCreateWindow("<%= @archivo.nombre %>");
	init();
	glutDisplayFunc(display);
	glutReshapeFunc(reshape);
	glutKeyboardFunc(keyboard);
	glutMainLoop();
	return 0;
}

</pre>
</div>

app/views/archivos/tarea2_v1.html.erb
<script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js"></script>

<script type="text/javascript">
$(document).ready(function(){

  $(document).ready(function() {
  	var clip = new ZeroClipboard($("#d_clip_button"))
  });

  $("#clear-test").on("click", function(){
    $("#fe_text").val("Copy me!");
    $("#testarea").val("");
  });
});

</script>
<div class="row">
  <div class="col-md-4">
	<p class="lead text-danger"><b>Tarea 2, primera versión:</b></p>
  </div>
  <div class="col-md-2 col-md-offset-4 text-right">
	  <button class='my_clip_button btn btn-success' data-clipboard-target='fe_text' data-clipboard-text='Default clipboard text from attribute' id='d_clip_button'>
	    Copia el código
	  </button>
  </div>
</div>
<pre class="prettyprint col-sm-10" id='fe_text'>
#include &#60;gl/glut.h&#62;

static float tz=0.0f;

static float cam=-15.0f;

void init(void);
void display(void);
void reshape(int, int);

void init(void){
	glClearColor(0.0,0.0,0.0,0.0);
	glShadeModel(GL_FLAT);
}

void dibujaFigura3D(){
   glutWireTeapot(5.0f);
}

void display(void){
	glClear(GL_COLOR_BUFFER_BIT);

		// Color
		glColor3f(0.38,0.73,1.0);
		dibujaFigura3D();

	glFlush();
}

void reshape(GLsizei w, GLsizei h){
	glViewport(0,0,w,h);
	glMatrixMode(GL_PROJECTION);
	glLoadIdentity();
	//glOrtho(-15,15,-15,15,-100,100);
    gluPerspective(60, 1, 0 , 100);
	gluLookAt(0,10,cam, 0,0,0, 0,1,0);
	glMatrixMode(GL_MODELVIEW);
}

void keyboard(unsigned char key, int x, int y){
     switch(key){
     	// controles para translacion
     	case 'e': tz += 0.3f;break;
     	case 'E': tz -= 0.3f;break;

     	case 'c': cam += 0.3f;break;
     	case 'C': cam -= 0.3f;break;
     }
     display();
     reshape(500,500);
}

int main(int argc, char** argv){
	glutInit(&argc, argv);
	glutInitDisplayMode(GLUT_SINGLE | GLUT_RGB);
	glutInitWindowSize(500,500);
	glutInitWindowPosition(100,100);
	glutCreateWindow("Ejercicio2");
	init();
	glutDisplayFunc(display);
	glutReshapeFunc(reshape);
	glutKeyboardFunc(keyboard);
	glutMainLoop();
	return 0;
}
</pre>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GeneradorOpengl</title>
  <%= stylesheet_link_tag    "application", media: "all"%>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="bs-example">
      <ul class="nav nav-pills">
        <li class="active"><a href="#">Examen Práctico de CAD</a></li>
		<li><%= link_to 'Tarea 1', archivos_new_path%></li>
		<li><%= link_to 'Tarea 2', tarea2_path%></li>
      </ul>
</div>

<div class="row">
	<div class="col-md-2">

	</div>
	<div class="col-md-10" role"main">
		<%= yield %>
	</div>
	<div class="col-md-2"></div>
</div>

</body>
</html>